# Spring properties
spring:
  application:
    name: PortalApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta
  flyway:
    enabled: false

server:
  port: 2222

#tailsocket:
#  port: 5555

management:     # If you set off security...
  security:
    enabled: false

# paasta info
#cloudfoundry:
#  cc:
#    api:
#      url: https://api.<DOMAIN>
#      uaaUrl: https://uaa.<DOMAIN>
#      sslSkipValidation: true
#  # CloudFoundry Login information
#  user:
#    admin:
#      username: admin
#      password: admin
#    uaaClient:
#      clientId: admin
#      clientSecret: admin-secret
#      adminClientId: admin
#      adminClientSecret: admin-secret
#      loginClientId: admin
#      loginClientSecret: admin-secret
#      skipSSLValidation: true
#  authorization: cf-Authorization


#abacus:
#  url: http://abacus.<DOMAIN>

# 포탈 상세 모니터링
#monitoring:
#  api:
#    url: http://monitoring.<DOMAIN>

multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb

#paasta:
#  portal:
#    api:
#      authorization:
#        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
#      zuulUrl:
#        cfapi: http://10.0.201.123:2225/portalapi
#        commonapi: http://10.0.201.123:2225/commonapi
#        storageapi: http://10.0.201.123:2225/storageapi
#    storageapi:
#      type: swift

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.201.124:2221/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10
